// Code generated by "stringer -type=ParamBindStyle"; DO NOT EDIT.

package sqlmapper

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BINDSTYLE_QUESTION-0]
	_ = x[BINDSTYLE_DOLLAR-1]
}

const _PreparedParamStyle_name = "PreparedParamStyle_MySQLPreparedParamStyle_Postgres"

var _PreparedParamStyle_index = [...]uint8{0, 24, 51}

func (i ParamBindStyle) String() string {
	if i < 0 || i >= ParamBindStyle(len(_PreparedParamStyle_index)-1) {
		return "ParamBindStyle(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PreparedParamStyle_name[_PreparedParamStyle_index[i]:_PreparedParamStyle_index[i+1]]
}
