// Code generated by "stringer -type=StatementParamType"; DO NOT EDIT.

package xml

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DollarParam-0]
	_ = x[DashParam-1]
}

const _StatementParamType_name = "DollarParamDashParam"

var _StatementParamType_index = [...]uint8{0, 11, 20}

func (i StatementParamType) String() string {
	if i < 0 || i >= StatementParamType(len(_StatementParamType_index)-1) {
		return "StatementParamType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatementParamType_name[_StatementParamType_index[i]:_StatementParamType_index[i+1]]
}
